name: Aliyun Deploy files
on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore: 'README.md'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        port: ${{ secrets.SERVER_PORT }}
        key: ${{ secrets.PRIVATE_KEY }}
        source: "*"
        target: "/root/code/common-apis"

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /root/code/common-apis
          npm install
          npm start